

export enum DiskAccessReadWrite {
    ENTIRE_VOLUME,
    ALL_PROGRAMS_AND_SAMPLES,
    ALL_PROGRAMS,
    ALL_SAMPLES,
    CURSOR_PROGRAMS_AND_SAMPLES,
    CURSOR_ITEM_ONLY,
    OPERATING_SYSTEM,
}

export enum DeleteFromDisk {
    CURSOR_ITEM_ONLY,
    ALL_PROGRAMS_ONLY,
    ALL_SAMPLES,
    ENTIRE_VOLUME,
    OPERATING_SYSTEM,
}
